const $=id=>document.getElementById(id), fa=n=>String(n).replace(/\d/g,d=>"۰۱۲۳۴۵۶۷۸۹"[d]);
const months=["فروردین","اردیبهشت","خرداد","تیر","مرداد","شهریور","مهر","آبان","آذر","دی","بهمن","اسفند"],week=["شنبه","یکشنبه","دوشنبه","سه‌شنبه","چهارشنبه","پنجشنبه","جمعه"];
let records=JSON.parse(localStorage.getItem("mahi_work")||"[]"), selected=null, cal=null;

function gregToJalali(gy,gm,gd){let gdm=[31,28,31,30,31,30,31,31,30,31,30,31],jy=gy<=1600?0:979, gy2=gy<=1600?gy-621:gy-1600;let gyL=gy2+1;let leap=gy2%4===0&&gy2%100!==0||gy2%400===0;let days=365*gy2+Math.floor((gyL+3)/4)-Math.floor((gyL+99)/100)+Math.floor((gyL+399)/400)-80+gd;for(let i=0;i<gm-1;i++)days+=gdm[i];if(gm>2&&leap)days++;jy+=33*Math.floor(days/12053);days%=12053;jy+=4*Math.floor(days/1461);days%=1461;if(days>365){jy+=Math.floor((days-1)/365);days=(days-1)%365}let jm=days<186?1+Math.floor(days/31):7+Math.floor((days-186)/30),jd=1+(days<186?days%31:(days-186)%30);return[jy,jm,jd]}
function jalaliToGregorian(jy,jm,jd){let gy=jy>979?1600:621,j=jy-(jy>979?979:0),days=365*j+Math.floor(j/33)*8+Math.floor((j%33+3)/4)+78+jd+(jm<7?(jm-1)*31:(jm-7)*30+186);gy+=400*Math.floor(days/146097);days%=146097;if(days>36524){gy+=100*Math.floor(--days/36524);days%=36524;if(days>=365)days++}gy+=4*Math.floor(days/1461);days%=1461;if(days>365){gy+=Math.floor((days-1)/365);days=(days-1)%365}let gd=days+1,gdm=[31,(gy%4===0&&gy%100!==0)||gy%400===0?29:28,31,30,31,30,31,31,30,31,30,31],gm=0;while(gd>gdm[gm])gd-=gdm[gm++];return new Date(gy,gm,gd)}
function pad(n){return String(n).padStart(2,"0")}
function dateObj(){let d=new Date();let [y,m,day]=gregToJalali(d.getFullYear(),d.getMonth()+1,d.getDate());return{y,m,day}}
function weekday(y,m,d){let g=jalaliToGregorian(y,m,d),n=g.getDay();return week[(n+1)%7]}
function openCal(){if(!cal){let t=dateObj();cal={y:t.y,m:t.m}}renderCal();$("calendarModal").classList.add("show")}
function renderCal(){let y=cal.y,m=cal.m;$("monthName").textContent=months[m-1];$("yearName").textContent=fa(y);let first=jalaliToGregorian(y,m,1),offset=(first.getDay()+1)%7, count=m<=6?31:(m<=11?30:((y%33===1||y%33===5||y%33===9||y%33===13||y%33===17||y%33===22||y%33===26||y%33===30)?30:29));let box=$("days");box.innerHTML="";for(let i=0;i<offset;i++){let e=document.createElement("button");e.className="empty-day";box.appendChild(e)}for(let d=1;d<=count;d++){let b=document.createElement("button");b.textContent=fa(d);if(selected&&selected[0]===y&&selected[1]===m&&selected[2]===d)b.classList.add("selected");let t=dateObj();if(t.y===y&&t.m===m&&t.day===d)b.classList.add("today");b.onclick=()=>chooseDate(y,m,d);box.appendChild(b)}}
function chooseDate(y,m,d){selected=[y,m,d];$("dateBtn").textContent=`${fa(y)}/${fa(pad(m))}/${fa(pad(d))}`;$("dayDisplay").textContent=weekday(y,m,d);$("calendarModal").classList.remove("show")}
function duration(a,b){let [h1,m1]=a.split(":").map(Number),[h2,m2]=b.split(":").map(Number);let x=h1*60+m1,y=h2*60+m2;if(y<x)y+=1440;return y-x}
function fmt(min){return `${fa(Math.floor(min/60))} ساعت و ${fa(min%60)} دقیقه`}
function save(){localStorage.setItem("mahi_work",JSON.stringify(records))}
function render(){let rows=$("rows");rows.innerHTML="";let total=records.reduce((s,r)=>s+r.min,0),days=new Set(records.map(r=>r.date)).size;$("monthHours").textContent=fa((total/60).toFixed(1));$("workDays").textContent=fa(days);$("avgHours").textContent=fa(days?(total/60/days).toFixed(1):"0");let t=dateObj(),today=`${t.y}/${pad(t.m)}/${pad(t.day)}`,tm=records.filter(r=>r.date===today).reduce((s,r)=>s+r.min,0);$("todayHours").textContent=fa((tm/60).toFixed(1));$("empty").style.display=records.length?"none":"block";records.forEach((r,i)=>{let tr=document.createElement("tr");tr.innerHTML=`<td>${r.date}</td><td>${r.day}</td><td>${r.start}</td><td>${r.end}</td><td>${fmt(r.min)}</td><td><button class="delete" onclick="removeRec(${i})">حذف</button></td>`;rows.appendChild(tr)});draw(total)}
function removeRec(i){records.splice(i,1);save();render()}
$("dateBtn").onclick=openCal;$("closeCal").onclick=()=>$("calendarModal").classList.remove("show");$("prevMonth").onclick=()=>{cal.m--;if(cal.m<1){cal.m=12;cal.y--}renderCal()};$("nextMonth").onclick=()=>{cal.m++;if(cal.m>12){cal.m=1;cal.y++}renderCal()};$("todayBtn").onclick=()=>{let t=dateObj();cal={y:t.y,m:t.m};chooseDate(t.y,t.m,t.day)}
$("addBtn").onclick=()=>{if(!selected)return alert("ابتدا تاریخ را انتخاب کنید.");let start=$("start").value,end=$("end").value;if(!start||!end)return alert("ساعت ورود و خروج را کامل وارد کنید.");if(start===end)return alert("ساعت ورود و خروج نمی‌تواند یکسان باشد.");let [y,m,d]=selected,ds=`${y}/${pad(m)}/${pad(d)}`;records.push({date:ds,day:weekday(y,m,d),start,end,min:duration(start,end)});save();render();$("start").value="";$("end").value=""}
$("clearBtn").onclick=()=>{if(confirm("همه ثبت‌ها پاک شوند؟")){records=[];save();render()}}
$("pdfBtn").onclick=()=>{if(!records.length)return alert("هنوز گزارشی برای ذخیره وجود ندارد.");let total=records.reduce((s,r)=>s+r.min,0);let html=`<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><title>گزارش ساعت کاری ماهی</title><style>body{font-family:Tahoma,Arial;padding:35px;color:#222}h1{text-align:center;color:#d6339c}p{text-align:center;color:#666}table{width:100%;border-collapse:collapse;margin-top:25px}th,td{border:1px solid #ddd;padding:10px;text-align:center}th{background:#f9d9ed}tfoot td{font-weight:bold;background:#f4e8f0}.summary{display:flex;gap:20px;justify-content:center;margin:20px 0}.box{padding:12px 20px;background:#f7edf5;border-radius:12px}</style></head><body><h1>ساعت کاری ماهی</h1><p>گزارش ساعت کاری</p><div class="summary"><div class="box">جمع کل: ${fmt(total)}</div><div class="box">روز کاری: ${fa(new Set(records.map(r=>r.date)).size)} روز</div></div><table><thead><tr><th>تاریخ</th><th>روز</th><th>ورود</th><th>خروج</th><th>مدت کار</th></tr></thead><tbody>${records.map(r=>`<tr><td>${r.date}</td><td>${r.day}</td><td>${r.start}</td><td>${r.end}</td><td>${fmt(r.min)}</td></tr>`).join("")}</tbody><tfoot><tr><td colspan="4">جمع کل</td><td>${fmt(total)}</td></tr></tfoot></table><script>window.onload=()=>setTimeout(()=>window.print(),400)<\/script></body></html>`;let w=window.open("","_blank");w.document.write(html);w.document.close()}
function draw(total){let c=$("barChart"),ctx=c.getContext("2d"),w=c.clientWidth,h=245,dpr=devicePixelRatio;c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);let groups={};records.forEach(r=>groups[r.date]=(groups[r.date]||0)+r.min/60);let arr=Object.entries(groups).slice(-12),max=Math.max(8,...arr.map(x=>x[1])),step=(w-45)/Math.max(arr.length,1),bw=Math.max(12,step-10);ctx.font="11px Tahoma";ctx.textAlign="center";arr.forEach(([d,v],i)=>{let x=35+i*step+5,y=h-35-v/max*(h-65);ctx.fillStyle="#ff55bd";ctx.shadowBlur=15;ctx.shadowColor="#ff55bd";ctx.fillRect(x,y,bw,h-35-y);ctx.shadowBlur=0;ctx.fillStyle="#cdbdca";ctx.fillText(d.slice(-5),x+bw/2,h-16);ctx.fillStyle="#fff";ctx.fillText(v.toFixed(1),x+bw/2,y-7)});ctx.strokeStyle="rgba(255,255,255,.1)";ctx.beginPath();ctx.moveTo(25,h-35);ctx.lineTo(w-10,h-35);ctx.stroke();let d=$("donutChart"),dc=d.getContext("2d"),dw=d.clientWidth,dh=245;d.width=dw*dpr;d.height=dh*dpr;dc.setTransform(dpr,0,0,dpr,0,0);let cx=dw/2,cy=122,r=82,pct=Math.min(total/60/176,1);dc.lineWidth=22;dc.lineCap="round";dc.beginPath();dc.strokeStyle="#403645";dc.arc(cx,cy,r,0,Math.PI*2);dc.stroke();dc.beginPath();dc.strokeStyle="#ff55bd";dc.shadowBlur=18;dc.shadowColor="#ff55bd";dc.arc(cx,cy,r,-Math.PI/2,-Math.PI/2+Math.PI*2*pct);dc.stroke();dc.shadowBlur=0;$("donutText").textContent=fa(Math.round(pct*100))+"٪"}
let t=dateObj();chooseDate(t.y,t.m,t.day);render();window.addEventListener("resize",render);
